#!/bin/bash
current_directory=$(pwd)
number_of_directories=$(find "$current_directory" -type d -mindepth 1 -not -path "$current_directory" -not -path "..")
echo "The number of directories and sub-directories in the current directory is $number_of_directories."

