#!/usr/bin/env bash
# This script will
# 1- make a file and put the pid in it
# 2- show a chain of strings
# 3- will del the file created in first step

terminator() {

  rm /var/run/myscript.pid

  exit

}

echo "$$" > /var/run/myscript.pid

while true

do

  echo "To infinity and beyond"

  sleep 2

  trap 'echo "Y U no love me?!"' SIGINT

  trap 'echo "I hate the kill command" && terminator' SIGTERM

  trap 'terminator' SIGQUIT

done
